		<form action='register.php' method='post'>
			<fieldset><center>
				<legend>
				Register for an Account
				</legend></center>
				<div style='padding-left:37px;'>
				<label>
					User name:
				</label>
				<div class='input-control text size4' data-role='input-control'>
					<input type='text' autofocus='' placeholder='User name' name='uname'></input>
					<button class='btn-clear' tabindex='-1' type='button'></button>
				</div>
				<label>
					Password:
				</label>
				<div class='input-control password size4' data-role='input-control'>
					<input type='Password' placeholder='password' name='pass'></input>
					<button class='btn-reveal' tabindex='-1' type='button'></button>
				</div>
				<label>
					Confirm Password:
				</label>
				<div class='input-control password size4' data-role='input-control'>
					<input type='Password' autofocus='' placeholder='password' name='repass'></input>
					<button class='btn-reveal' tabindex='-1' type='button'></button>
				</div>
				<label>
					Full name:
				</label>
				<div class='input-control text size4' data-role='input-control'>
					<input type='text' placeholder='full name' name='fullname'></input>
					<button class='btn-clear' tabindex='-1' type='button'></button>
				</div>
				<label>
					Birthday:
				</label>
				<div class='input-control text size4' data-role='datepicker' data-week-start='1'>
					<input type='text' readonly='readonly' autofocus='' placeholder='birthday' name='birthday'></input>
					<button class='btn-date' type='button'></button>
				</div>
				<label>
					Job:
				</label>
				<div class='input-control text size4' data-role='input-control'>
					<input type='text' autofocus='' placeholder='job' name='job'></input>
					<button class='btn-clear' tabindex='-1' type='button'></button>
				</div>
				<label>
					Nationality:
				</label>
				<div class='input-control text size4' data-role='input-control'>
					<input type='text' autofocus='' placeholder='nationality' name='nationality'></input>
					<button class='btn-clear' tabindex='-1' type='button'></button>
				</div>
				<label>
					Balance:
				</label>
				<div class='input-control text size4' data-role='input-control'>
					<input type='text' autofocus='' placeholder='balance' name='balance'></input>
					<button class='btn-clear' tabindex='-1' type='button'></button>
				</div>
				<br><br>
				<input type='submit' value='Create Account'></input>
				</div>
			</fieldset>
		</form>